Fully working on derecho!

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -12,8 +12,7 @@ set -euo pipefail # exit on failure or unset variable
 #set -x  # show all the commands that are being executed
 
 export SLURM_BUILDKITE_PATH="$(dirname "${BUILDKITE_BIN_PATH}")"
-# export GIT_SSH_COMMAND="ssh -i ${SLURM_BUILDKITE_PATH}/.ssh/id_rsa -o IdentitiesOnly=yes"
-export SHARED_DEPOT="${BUILDKITE_BUILD_PATH}/shared_depot"
+export GIT_SSH_COMMAND="ssh -i ${SLURM_BUILDKITE_PATH}/.ssh/id_rsa -o IdentitiesOnly=yes"
 export CI_BUILD_DIR="${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/${BUILDKITE_BUILD_NUMBER}"
 export JULIA_DEPOT_PATH="${JULIA_DEPOT_PATH:-$CI_BUILD_DIR/depot/default}"
 export BUILDKITE_BUILD_CHECKOUT_PATH="${CI_BUILD_DIR}/${BUILDKITE_PIPELINE_SLUG}"
@@ -29,8 +28,12 @@ if [ "$BUILDKITE_AGENT_META_DATA_QUEUE" != "derecho" ]; then
     export TMPDIR="/tmp/slurm-${SLURM_JOB_ID}"
 else
     echo "--- PBS Job ID: ${PBS_JOBID}"
-    # qstat ${PBS_JOBID}
-    # pbsnodes $(head -1 ${PBS_NODEFILE})
+    qstat -f ${PBS_JOBID} || {
+        echo "Error: qstat failed" >&2
+    }
+    echo "Current nodes:"
+    cat $PBS_NODEFILE
+    # TODO: This should live in scratch on derecho
     export TMPDIR="/tmp/pbs-${PBS_JOBID}"
 fi
 
